### ISSUE TITLE
Parser fails on classic elbs

### ISSUE THREAD

**Issue by PavelVaks** [dpetzold/aws-log-parser#15]
Hi,
The parser only works with application LBs (ElbV2), and fails on classic Elb logs
classic Lb logs entries are different between application\network logs:
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/access-log-collection.html#access-log-entry-format
vs 
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-format

**Comment by PavelVaks** [comment]
I have fixed it and created a pull request :)
https://github.com/dpetzold/aws-log-parser/pull/16

Thanks!

**Comment by dpetzold** [comment]
Merged!
