### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by dpetzold** [dpetzold/aws-log-parser#2]
Needs better docs

**Comment by rnason-mmi** [comment]
I would love to use this, but loading a log file yields the following error:

iterator should return strings, not int (did you open the file in text mode?)

Documentation doesn't give any context, what format is this module accepting. I am trying to parse ALB logs in their default format, also tried decoding each event and that was still a no-go.  No documentation, no context = not usable unfortunately... Was really hoping I wouldn't have to write my own parser :(

**Comment by dpetzold** [comment]
I added some helper methods and updated the docs. Please see if the new README is more clear.
