### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by tiggeymone** [dpetzold/aws-log-parser#25]
Hello, I'm having the following error after installing from pip:

ModuleNotFoundError: No module named 'aws_log_parser.aws'

Exploring the files, it seems that the .aws subfolder is not created inside aws_log_parser.

I tried also to downgrade to the 1.x versions, but I still have the same problem.

What am I doing wrong?

Thank you in advance

**Comment by dpetzold** [comment]
Hello,

The submodule was missing from the wheel distribution. I uploaded a new version `2.1.0`. Please give it a shot.

Derrick
