### ISSUE TITLE
Parse a single line?

### ISSUE THREAD

**Issue by acutchin-bitpusher** [dpetzold/aws-log-parser#31]
I might want to download and open an ALB log file from S3 outside of aws-log-parser to circumvent memory issues with very large log files. Is there a way to use aws-log-parser to parse a single log line?

**Comment by dpetzold** [comment]
Hello @acutchin-bitpusher,

To parse a single line you would do something like this:

```
entries = parser.parse([log_line])
```

Best,
  Derrick
